In [1]:
#Basic libraries
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
from collections import Counter
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')
# library used for over sampling the data
from imblearn.over_sampling import RandomOverSampler

In [2]:
dataset = pd.read_csv('C:/Users/Bel_Z_Man/Desktop/data_set.csv',sep=',',index_col='id')

In [3]:
dataset.shape

(29104, 24)

In [4]:
X=dataset.drop('v457',axis=1)
y=dataset.v457

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

In [6]:
X_train.shape,y_train.shape, X_test.shape, y_test.shape

((23283, 23), (23283,), (5821, 23), (5821,))

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,roc_auc_score,precision_score,recall_score,f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.multiclass import OneVsOneClassifier
RF = RandomForestClassifier(criterion='entropy',max_features='sqrt',min_samples_split=3,n_estimators=500,random_state=0,max_depth=20, max_leaf_nodes=400, n_jobs=-1)
ovo = OneVsOneClassifier(RF)
ovo.fit(X_train, y_train)
pred = ovo.predict(X_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           1       0.98      1.00      0.99      1491
           2       0.95      0.92      0.94      1449
           3       0.93      0.95      0.94      1454
           4       0.92      0.90      0.91      1427

    accuracy                           0.94      5821
   macro avg       0.94      0.94      0.94      5821
weighted avg       0.94      0.94      0.94      5821



In [8]:
accuracy=accuracy_score(y_test,pred)
accuracy

0.9439958769970795

In [9]:
print("",confusion_matrix(y_test,pred))

 [[1487    1    1    2]
 [  24 1337   38   50]
 [   8   10 1380   56]
 [   3   61   72 1291]]


In [10]:
precision=precision_score(y_test, pred, pos_label='positive',average='macro')
precision

0.9435647981395323

In [11]:
recall=recall_score(y_test, pred,pos_label='positive',average='macro')
recall

0.9434559075406718

In [12]:
from sklearn import model_selection
kfold = model_selection.KFold(n_splits=10)
results = model_selection.cross_val_score(ovo, X,y.values.ravel(),scoring='accuracy', cv=kfold)

In [13]:
cross_vall=results.mean()
cross_vall

0.8936967020461551

In [14]:
f1_score=f1_score(y_test, pred,pos_label='positive',average='macro')
f1_score

0.9433789875324927

In [18]:
ROC_with_ovo=roc_auc_score(y, ovo.decision_function(X), multi_class='ovo')
ROC_with_ovo

ValueError: Target scores need to be probabilities for multiclass roc_auc, i.e. they should sum up to 1.0 over classes

In [17]:
ROC_with_ovr=roc_auc_score(y, ovo.decision_function(X), multi_class='ovr')
ROC_with_ovr

AttributeError: 'OneVsOneClassifier' object has no attribute 'predict_proba'

In [15]:
RF_ovo= pd.DataFrame({'accuracy':accuracy,
                   'precision':precision,'recall':recall,'cross_vall':cross_vall,'f1_score':f1_score},
       columns=['accuracy','precision','recall','cross_vall','f1_score'],index=["performance"])
RF_ovo

accuracy  precision    recall  cross_vall  f1_score
performance  0.943996   0.943565  0.943456    0.893697  0.943379