In [1]:
#Basic libraries
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
from collections import Counter
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')
# library used for over sampling the data
from imblearn.over_sampling import RandomOverSampler

In [2]:
dataset = pd.read_csv('C:/Users/Bel_Z_Man/Desktop/data_set.csv',sep=',',index_col='id')

In [3]:
dataset.shape

(29104, 24)

In [4]:
X=dataset.drop('v457',axis=1)
y=dataset.v457

In [5]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

In [6]:
X_train.shape,y_train.shape, X_test.shape, y_test.shape

((23283, 23), (23283,), (5821, 23), (5821,))

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,roc_auc_score,precision_score,recall_score,f1_score
from xgboost import XGBClassifier
from sklearn.multiclass import OneVsRestClassifier
model = XGBClassifier()
ovr = OneVsRestClassifier(model)
ovr.fit(X_train, y_train)
pred = ovr.predict(X_test)
print(classification_report(y_test,pred))

[15:14:17] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[15:19:01] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[15:27:00] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[15:33:14] WARNING: C:/Users/Administrator/workspace/xgboost-win64_rel

In [8]:
accuracy=accuracy_score(y_test,pred)
accuracy

0.9453702113038996

In [9]:
print("",confusion_matrix(y_test,pred))

 [[1485    3    2    1]
 [  14 1375   37   23]
 [   6   48 1357   43]
 [   6   55   80 1286]]


In [10]:
precision=precision_score(y_test, pred, pos_label='positive',average='macro')
precision

0.9452691746919197

In [11]:
recall=recall_score(y_test, pred,pos_label='positive',average='macro')
recall

0.9448462362836766

In [12]:
f1_score=f1_score(y_test, pred,pos_label='positive',average='macro')
f1_score

0.9448416780510556

In [13]:
from sklearn import model_selection
kfold = model_selection.KFold(n_splits=10)
results = model_selection.cross_val_score(ovr, X,y.values.ravel(),scoring='accuracy', cv=kfold)

[15:34:45] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[15:35:16] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[15:35:57] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[15:36:28] WARNING: C:/Users/Administrator/workspace/xgboost-win64_rel

[15:51:20] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[15:51:49] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[15:52:10] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[15:52:30] WARNING: C:/Users/Administrator/workspace/xgboost-win64_rel

In [14]:
cross_val=results.mean()
cross_val

0.8971702783965549

In [15]:
ROCx_with_xgb_ovr=roc_auc_score(y, ovr.predict_proba(X), multi_class='ovr')
ROCx_with_xgb_ovr

0.9954392986276938

In [16]:
ROCx_with_xgb_ovo=roc_auc_score(y, ovr.predict_proba(X), multi_class='ovo')
ROCx_with_xgb_ovo

0.9954392986276938

In [17]:
xgb = pd.DataFrame({'accuracy':accuracy,
                   'precision':precision,'recall':recall,'cross_val':cross_val,'f1_score':f1_score,'ROCx_with_xgb_ovo':ROCx_with_xgb_ovo,'ROCx_with_xgb_ovr':ROCx_with_xgb_ovr},
       columns=['accuracy','precision','recall','cross_val','f1_score','ROCx_with_xgb_ovo','ROCx_with_xgb_ovr'],index=["performance"])
xgb

accuracy  precision    recall  cross_val  f1_score  \
performance   0.94537   0.945269  0.944846    0.89717  0.944842   

             ROCx_with_xgb_ovo  ROCx_with_xgb_ovr  
performance           0.995439           0.995439

In [18]:
metrics.plot_roc_curve(ovr, X_test, y_test) 

<IPython.core.display.Javascript object>

ValueError: OneVsRestClassifier should be a binary classifier