In [1]:
#Basic libraries
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
from collections import Counter
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')
# library used for over sampling the data
from imblearn.over_sampling import RandomOverSampler

In [2]:
dataset = pd.read_csv('C:/Users/Bel_Z_Man/Desktop/data_set.csv',sep=',',index_col='id')

In [3]:
dataset.shape

(29104, 24)

In [4]:
X=dataset.drop('v457',axis=1)
y=dataset.v457

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

In [6]:
X_train.shape,y_train.shape, X_test.shape, y_test.shape

((23283, 23), (23283,), (5821, 23), (5821,))

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,roc_auc_score,precision_score,recall_score,f1_score
from xgboost import XGBClassifier
xgb_clf = XGBClassifier()
xgb_clf.fit(X_train, y_train)
pred = xgb_clf.predict(X_test)
print(classification_report(y_test,pred))

[15:14:23] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
              precision    recall  f1-score   support

           1       0.97      1.00      0.98      1491
           2       0.93      0.94      0.93      1449
           3       0.92      0.95      0.93      1454
           4       0.95      0.89      0.92      1427

    accuracy                           0.94      5821
   macro avg       0.94      0.94      0.94      5821
weighted avg       0.94      0.94      0.94      5821



In [8]:
accuracy=accuracy_score(y_test,pred)
accuracy

0.9426215426902594

In [9]:
print("",confusion_matrix(y_test,pred))

 [[1484    4    2    1]
 [  21 1362   39   27]
 [  15   29 1376   34]
 [  11   72   79 1265]]


In [10]:
precision=precision_score(y_test, pred, pos_label='positive',average='macro')
precision

0.9426976588379343

In [11]:
recall=recall_score(y_test, pred,pos_label='positive',average='macro')
recall

0.9420234405419521

In [12]:
from sklearn import model_selection
kfold = model_selection.KFold(n_splits=10)
results = model_selection.cross_val_score(xgb_clf, X,y.values.ravel(),scoring='accuracy', cv=kfold)

[15:34:47] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[15:37:06] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[15:39:16] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[15:42:01] WARNING: C:/Users/Administrator/workspace/xgboost-win64_

In [13]:
cross_val=results.mean()
cross_val

0.8885789297852323

In [14]:
f1_score=f1_score(y_test, pred,pos_label='positive',average='macro')
f1_score

0.941958133845258

In [15]:
roc_xgb_with_ovo=roc_auc_score(y, xgb_clf.predict_proba(X), multi_class='ovo')
roc_xgb_with_ovo

0.9953430673646925

In [16]:
roc_xgb_with_ovr=roc_auc_score(y, xgb_clf.predict_proba(X), multi_class='ovr')
roc_xgb_with_ovr

0.9953430673646921

In [17]:
xgb = pd.DataFrame({'accuracy':accuracy,
                   'precision':precision,'recall':recall,'cross_val':cross_val,'f1_score':f1_score,'roc_xgb_with_ovo':roc_xgb_with_ovo,'roc_xgb_with_ovr':roc_xgb_with_ovr},
       columns=['accuracy','precision','recall','cross_val','f1_score','roc_xgb_with_ovo','roc_xgb_with_ovr'],index=["performance"])
xgb

accuracy  precision    recall  cross_val  f1_score  \
performance  0.942622   0.942698  0.942023   0.888579  0.941958   

             roc_xgb_with_ovo  roc_xgb_with_ovr  
performance          0.995343          0.995343