In [1]:
#Basic libraries
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
from collections import Counter
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')
# library used for over sampling the data
from imblearn.over_sampling import RandomOverSampler

In [2]:
dataset = pd.read_csv('C:/Users/Bel_Z_Man/Desktop/data_set.csv',sep=',',index_col='id')

In [3]:
dataset.shape

(29104, 24)

In [4]:
X=dataset.drop('v457',axis=1)
y=dataset.v457

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

In [6]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,roc_auc_score,precision_score,recall_score,f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.multiclass import OneVsRestClassifier
Dt = DecisionTreeClassifier(criterion='entropy',max_features='sqrt',min_samples_split=12,random_state=0,max_depth=30, max_leaf_nodes=600)
ovr = OneVsRestClassifier(Dt)
ovr.fit(X_train, y_train)
pred = ovr.predict(X_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           1       0.98      0.99      0.99      1491
           2       0.86      0.89      0.88      1449
           3       0.84      0.87      0.86      1454
           4       0.87      0.81      0.84      1427

    accuracy                           0.89      5821
   macro avg       0.89      0.89      0.89      5821
weighted avg       0.89      0.89      0.89      5821



In [7]:
accuracy=accuracy_score(y_test,pred)
accuracy

0.8909122143961519

In [8]:
print("",confusion_matrix(y_test,pred))

 [[1480    2    6    3]
 [  11 1285   90   63]
 [   7   81 1261  105]
 [  11  118  138 1160]]


In [9]:
precision=precision_score(y_test, pred, pos_label='positive',average='macro')
precision

0.8901307388010548

In [10]:
recall=recall_score(y_test, pred,pos_label='positive',average='macro')
recall

0.8898994509276339

In [11]:
from sklearn import model_selection
kfold = model_selection.KFold(n_splits=10)
results = model_selection.cross_val_score(ovr, X,y.values.ravel(),scoring='accuracy', cv=kfold)

In [12]:
cross_val=results.mean()
cross_val

0.8317810272919051

In [13]:
f1_score=f1_score(y_test, pred,pos_label='positive',average='macro')
f1_score

0.8896749825271886

In [14]:
RF_ovr= pd.DataFrame({'accuracy':accuracy,
                   'precision':precision,'recall':recall,'cross_val':cross_val,'f1_score':f1_score},
       columns=['accuracy','precision','recall','cross_val','f1_score'],index=["performance"])
RF_ovr

accuracy  precision    recall  cross_val  f1_score
performance  0.890912   0.890131  0.889899   0.831781  0.889675