In [1]:
#Basic libraries
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
from collections import Counter
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')
# library used for over sampling the data
from imblearn.over_sampling import RandomOverSampler

In [2]:
dataset = pd.read_csv('C:/Users/Bel_Z_Man/Desktop/data_set.csv',sep=',',index_col='id')

In [3]:
dataset.shape

(29104, 24)

In [4]:
X=dataset.drop('v457',axis=1)
y=dataset.v457

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

In [6]:
X_train.shape,y_train.shape, X_test.shape, y_test.shape

((23283, 23), (23283,), (5821, 23), (5821,))

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,roc_auc_score,precision_score,recall_score,f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.multiclass import OneVsRestClassifier
RF = RandomForestClassifier(criterion='entropy',max_features='sqrt',min_samples_split=3,n_estimators=500,random_state=0,max_depth=20, max_leaf_nodes=400, n_jobs=-1)
ovr = OneVsRestClassifier(RF)
ovr.fit(X_train, y_train)
pred = ovr.predict(X_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           1       0.97      1.00      0.98      1491
           2       0.95      0.91      0.93      1449
           3       0.93      0.95      0.94      1454
           4       0.93      0.91      0.92      1427

    accuracy                           0.94      5821
   macro avg       0.94      0.94      0.94      5821
weighted avg       0.94      0.94      0.94      5821



In [8]:
accuracy=accuracy_score(y_test,pred)
accuracy

0.9439958769970795

In [9]:
print("",confusion_matrix(y_test,pred))

 [[1489    1    1    0]
 [  28 1325   45   51]
 [  16    8 1379   51]
 [  10   56   59 1302]]


In [10]:
precision=precision_score(y_test, pred, pos_label='positive',average='macro')
precision

0.9437090902204843

In [11]:
recall=recall_score(y_test, pred,pos_label='positive',average='macro')
recall

0.9434760399262094

In [12]:
from sklearn import model_selection
kfold = model_selection.KFold(n_splits=10)
results = model_selection.cross_val_score(ovr, X,y.values.ravel(),scoring='accuracy', cv=kfold)

In [13]:
cross_val=results.mean()
cross_val

0.8817724923002098

In [14]:
f1_score=f1_score(y_test, pred,pos_label='positive',average='macro')
f1_score

0.9433799832774094

In [15]:
roc_ovr=roc_auc_score(y, ovr.predict_proba(X), multi_class='ovr')

In [16]:
roc_ovr

0.994349121544288

In [17]:
roc_ovo=roc_auc_score(y, ovr.predict_proba(X), multi_class='ovo')

In [18]:
roc_ovo

0.994349121544288

In [19]:
RF_ovr= pd.DataFrame({'accuracy':accuracy,
                   'precision':precision,'recall':recall,'cross_val':cross_val,'f1_score':f1_score,'roc_ovr':roc_ovr,'roc_ovo':roc_ovo},
       columns=['accuracy','precision','recall','cross_val','f1_score','roc_ovr','roc_ovo'],index=["performance"])
RF_ovr

accuracy  precision    recall  cross_val  f1_score   roc_ovr  \
performance  0.943996   0.943709  0.943476   0.881772   0.94338  0.994349   

              roc_ovo  
performance  0.994349