In [1]:
#Basic libraries
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
from collections import Counter
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')
# library used for over sampling the data
from imblearn.over_sampling import RandomOverSampler

In [2]:
dataset = pd.read_csv('C:/Users/Bel_Z_Man/Desktop/data_set.csv',sep=',',index_col='id')

In [3]:
dataset.shape

(29104, 24)

In [4]:
X=dataset.drop('v457',axis=1)
y=dataset.v457

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

In [6]:
X_train.shape,y_train.shape, X_test.shape, y_test.shape

((23283, 23), (23283,), (5821, 23), (5821,))

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,roc_auc_score,precision_score,recall_score,f1_score
from sklearn.svm import SVC
from sklearn.multiclass import OneVsOneClassifier
SVM = SVC()
ovo = OneVsOneClassifier(SVM)
ovo.fit(X_train, y_train)
pred = ovo.predict(X_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           1       0.71      0.93      0.80      1491
           2       0.55      0.50      0.52      1449
           3       0.56      0.51      0.53      1454
           4       0.61      0.52      0.56      1427

    accuracy                           0.62      5821
   macro avg       0.61      0.61      0.61      5821
weighted avg       0.61      0.62      0.61      5821



In [8]:
accuracy=accuracy_score(y_test,pred)
accuracy

0.6170761037622402

In [9]:
print("",confusion_matrix(y_test,pred))

 [[1385   46   39   21]
 [ 269  728  259  193]
 [ 153  304  744  253]
 [ 147  247  298  735]]


In [10]:
precision=precision_score(y_test, pred, pos_label='positive',average='macro')
precision

0.6062352911463199

In [11]:
recall=recall_score(y_test, pred,pos_label='positive',average='macro')
recall

0.6145201726504049

In [12]:
from sklearn import model_selection
kfold = model_selection.KFold(n_splits=10)
results = model_selection.cross_val_score(ovo, X,y.values.ravel(),scoring='accuracy', cv=kfold)

In [13]:
cross_val=results.mean()
cross_val

0.4064724867518749

In [14]:
f1_score=f1_score(y_test, pred,pos_label='positive',average='macro')
f1_score

0.6051638616230712

In [15]:
RF_ovr= pd.DataFrame({'accuracy':accuracy,
                   'precision':precision,'recall':recall,'cross_val':cross_val,'f1_score':f1_score},
       columns=['accuracy','precision','recall','cross_val','f1_score'],index=["performance"])
RF_ovr

accuracy  precision   recall  cross_val  f1_score
performance  0.617076   0.606235  0.61452   0.406472  0.605164