In [1]:
#Basic libraries
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
from collections import Counter
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')
# library used for over sampling the data
from imblearn.over_sampling import RandomOverSampler

In [2]:
dataset = pd.read_csv('C:/Users/Bel_Z_Man/Desktop/data_set.csv',sep=',',index_col='id')

In [3]:
dataset.shape

(29104, 24)

In [4]:
X=dataset.drop('v457',axis=1)
y=dataset.v457

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

In [6]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,roc_auc_score,precision_score,recall_score,f1_score
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
SVM = SVC()
ovr = OneVsRestClassifier(SVM)
ovr.fit(X_train, y_train)
pred = ovr.predict(X_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           1       0.66      0.97      0.79      1491
           2       0.67      0.51      0.58      1449
           3       0.68      0.53      0.60      1454
           4       0.61      0.60      0.61      1427

    accuracy                           0.66      5821
   macro avg       0.66      0.65      0.64      5821
weighted avg       0.66      0.66      0.64      5821



In [7]:
accuracy=accuracy_score(y_test,pred)
accuracy

0.6553856725648514

In [8]:
print("",confusion_matrix(y_test,pred))

 [[1441   12   17   21]
 [ 330  735  134  250]
 [ 205  196  776  277]
 [ 201  153  210  863]]


In [9]:
precision=precision_score(y_test, pred, pos_label='positive',average='macro')
precision

0.6566653187802846

In [10]:
recall=recall_score(y_test, pred,pos_label='positive',average='macro')
recall

0.6530443038880811

In [ ]:
from sklearn import model_selection
kfold = model_selection.KFold(n_splits=10)
results = model_selection.cross_val_score(ovr, X,y.values.ravel(),scoring='accuracy', cv=kfold)

In [ ]:
cross_val=results.mean()
cross_val

In [ ]:
f1_score=f1_score(y_test, pred,pos_label='positive',average='macro')
f1_score

In [ ]:
RF_ovr= pd.DataFrame({'accuracy':accuracy,
                   'precision':precision,'recall':recall,'cross_val':cross_val,'f1_score':f1_score},
       columns=['accuracy','precision','recall','cross_val','f1_score'],index=["performance"])
RF_ovr