In [1]:
#Basic libraries
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
from collections import Counter
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')
# library used for over sampling the data
from imblearn.over_sampling import RandomOverSampler

In [2]:
dataset = pd.read_csv('C:/Users/Bel_Z_Man/Desktop/data_set.csv',sep=',',index_col='id')

In [3]:
dataset.shape

(29104, 25)

In [4]:
X=dataset.drop('v457',axis=1)
y=dataset.v457

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

In [6]:
X_train.shape,y_train.shape, X_test.shape, y_test.shape

((23283, 24), (23283,), (5821, 24), (5821,))

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,roc_auc_score,precision_score,recall_score,f1_score
from sklearn.multiclass import OneVsOneClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
base_estimator=DecisionTreeClassifier(max_depth=200,max_leaf_nodes=400,criterion='entropy', splitter='best', min_samples_split=2)
model = AdaBoostClassifier(base_estimator=base_estimator,n_estimators=50,learning_rate=0.001)
ovo = OneVsOneClassifier(model)
ovo.fit(X_train, y_train)
pred = ovo.predict(X_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           1       0.99      1.00      0.99      1491
           2       0.97      0.96      0.96      1449
           3       0.94      0.94      0.94      1454
           4       0.94      0.94      0.94      1427

    accuracy                           0.96      5821
   macro avg       0.96      0.96      0.96      5821
weighted avg       0.96      0.96      0.96      5821



In [8]:
accuracy=accuracy_score(y_test,pred)
accuracy

0.9589417625837485

In [9]:
print("",confusion_matrix(y_test,pred))

 [[1487    1    2    1]
 [   7 1384   33   25]
 [   5   16 1369   64]
 [   4   33   48 1342]]


In [10]:
precision=precision_score(y_test, pred, pos_label='positive',average='macro')
precision

0.9586188560379945

In [11]:
recall=recall_score(y_test, pred,pos_label='positive',average='macro')
recall

0.9586084423192065

In [12]:
from sklearn import model_selection
kfold = model_selection.KFold(n_splits=10)
results = model_selection.cross_val_score(ovo, X,y.values.ravel(),scoring='accuracy', cv=kfold)

In [13]:
cross_val=results.mean()
cross_val

0.9411797648686522

In [14]:
f1_score=f1_score(y_test, pred,pos_label='positive',average='macro')
f1_score

0.9586023326926769

In [17]:
adaboosted_dt_ovo = pd.DataFrame({'accuracy':accuracy,
                   'precision':precision,'recall':recall,'cross_val':cross_val,'f1_score':f1_score},
       columns=['accuracy','precision','recall','cross_val','f1_score'],index=["performance"])
adaboosted_dt_ovo

accuracy  precision    recall  cross_val  f1_score
performance  0.958942   0.958619  0.958608    0.94118  0.958602